Updated .in file.

diff --git a/rankmirrors.sh.in b/rankmirrors.sh.in
--- a/rankmirrors.sh.in
+++ b/rankmirrors.sh.in
@@ -35,7 +35,7 @@ usage() {
 	echo "  -t, --times    only output mirrors and their response times"
 	echo "  -u, --url      test a specific url"
 	echo "  -v, --verbose  be verbose in ouptut"
-	exit
+	exit 0
 }
 
 version() {
@@ -44,7 +44,7 @@ version() {
 	echo
 	echo "This is free software; see the source for copying conditions."
 	echo "There is NO WARRANTY, to the extent permitted by law."
-	exit
+	exit 0
 }
 
 err() {
@@ -55,7 +55,7 @@ err() {
 # gettime fetchurl (e.g gettime http://foo.com/core/os/i686/core.db.tar.gz)
 # returns the fetching time, or timeout, or unreachable
 gettime() {
-	output=( $(curl -s -m 10 -w "%{time_total} %{http_code}" "$1" -o/dev/null) )
+	IFS=' ' output=( $(curl -s -m 10 -w "%{time_total} %{http_code}" "$1" -o/dev/null) )
 	[[ $? = 28 ]] && echo timeout && return
 	[[ ${output[1]} -ge 400 || ${output[1]} -eq 0 ]] && echo unreachable && return
 	echo "${output[0]}"
@@ -63,17 +63,23 @@ gettime() {
 
 # getfetchurl serverurl (e.g. getturl http://foo.com/core/os/i686)
 # if $repo is in the line, then assumes core
+# if $arch is in the line, then assumes $(uname -m)
 # returns a fetchurl (e.g. http://foo.com/core/os/i686/core.db.tar.gz)
+ARCH="$(uname -m)"
 getfetchurl() {
-	strippedurl="${1%/}"
-	replacedurl="${strippedurl//'$repo'/core}"
-	tmp1="${replacedurl%/*}"
-	tmp2="${tmp1%/*}"
-	reponame="${tmp2##*/}"
+	local strippedurl="${1%/}"
+
+	local replacedurl="${strippedurl//'$repo'/core}"
+	replacedurl="${replacedurl//'$arch'/$ARCH}"
+
+	local tmp="${replacedurl%/*}"
+	tmp="${tmp%/*}"
+
+	local reponame="${tmp##*/}"
 	if [[ -z $reponame || $reponame = $replacedurl ]]; then
 		echo "fail"
 	else
-		fetchurl="${replacedurl}/$reponame@DBEXT@"
+		local fetchurl="${replacedurl}/$reponame@DBEXT@"
 		echo "$fetchurl"
 	fi
 }
@@ -99,7 +105,7 @@ finaloutput() {
 			[[ $NUM -ne 0 && $numiterator -ge $NUM ]] && break
 		done
 	fi
-	exit
+	exit 0
 }
 
 
@@ -115,21 +121,31 @@ while [[ $1 ]]; do
 			url) CHECKURL=1; [[ $2 ]] || err "Must specify url."; URL="$2"; shift 2;; 
 			*) err "\`$1' is an invalid argument."
 		esac
-	elif [[ "${1:0:1}" = - ]]; then
-		snum=1
-		for ((i=1 ; i<${#1}; i++)); do
-			case ${1:$i:1} in
-				h) usage ;;
-				t) TIMESONLY=1 ;;
-				v) VERBOSE=1 ;;
-				u) CHECKURL=1; [[ $2 ]] || err "Must specify url."; URL="$2"; snum=2;;
-				n) [[ $2 ]] || err "Must specify number." ; NUM="$2" ; snum=2;;
-				*) err "\`-$1' is an invald argument." ;;
-			esac
-		done
-		shift $snum
+	elif [[ ${1:0:1} = - ]]; then
+
+		if [[ ! ${1:1:1} ]]; then
+			[[ -t 0 ]] && err "Stdin is empty."
+			IFS=$'\n' linearray=( $(</dev/stdin) )
+			STDIN=1
+			shift
+		else
+			snum=1
+			for ((i=1 ; i<${#1}; i++)); do
+				case ${1:$i:1} in
+					h) usage ;;
+					t) TIMESONLY=1 ;;
+					v) VERBOSE=1 ;;
+					u) CHECKURL=1; [[ $2 ]] || err "Must specify url."; URL="$2"; snum=2;;
+					n) [[ $2 ]] || err "Must specify number." ; NUM="$2" ; snum=2;;
+					*) err "\`-$1' is an invald argument." ;;
+				esac
+			done
+			shift $snum
+		fi
 	elif [[ -f "$1" ]]; then
-		FILE="$1"
+		FILE="1"
+		IFS=$'\n' linearray=( $(<$1) )
+		[[ $linearray ]] || err "File is empty."
 		shift
 	else
 		err "\`$1' does not exist."
@@ -138,27 +154,28 @@ done
 
 # Some sanity checks
 [[ $NUM ]] || NUM=0
-[[ $FILE && $URL ]] && err "Cannot specify a url and mirrorfile."
-[[ $FILE || $URL ]] || err "Must specify url or mirrorfile."
+[[ $FILE && $CHECKURL ]] && err "Cannot specify a url and mirrorfile."
+[[ $FILE || $CHECKURL || $STDIN ]] || err "Must specify url, mirrorfile, or stdin."
 
 # Single url handling
 if [[ $CHECKURL ]]; then
 	url="$(getfetchurl "$URL")"
 	[[ $url = fail ]] && err "url \`$URL' is malformed."
 	[[ $VERBOSE ]] && echo "Testing $url..."
-	time="$(gettime "$url")"
+	time=$(gettime "$url")
 	echo "$URL : $time"
-	exit
+	exit 0
 fi
 
 # Get url results from mirrorfile, fill up the array, and so on
 if [[ $TIMESONLY ]]; then
 	echo "Querying servers, this may take some time..."
-else
+elif [[ $FILE ]]; then
 	echo "# Server list generated by rankmirrors on $(date +%Y-%m-%d)"
 fi
 
-while read line; do
+timesarray=()
+for line in  "${linearray[@]}"; do
 	if [[ $line =~ ^# ]]; then
 		[[ $TIMESONLY ]] || echo $line
 	elif [[ $line =~ ^Server ]]; then
@@ -168,8 +185,7 @@ while read line; do
 		url="$(getfetchurl "$server")"
 		[[ $url = fail ]] && err "url \`$URL' is malformed."
 		time=$(gettime "$url")
-
-		timesarray=( "${timesarray[@]}" "$time $server" )
+		timesarray+=("$time $server")
 
 		# Output
 		if [[ $VERBOSE && $TIMESONLY ]]; then
@@ -180,7 +196,7 @@ while read line; do
 			echo -n "   *"
 		fi
 	fi
-done <"$FILE"
+done
 finaloutput
 
 # vim: set ts=2 sw=2 noet:
